### ISSUE TITLE
Run the import job as an Azure Container Instance

### ISSUE THREAD

**Issue by ssemyan** [retaildevcrews/imdb#52]
Rather than running the import job locally via dotnet or docker, just run it as an Azure Container Instance:

```
export Imdb_Aci=${Imdb_Name}-aci

az container create -g $Imdb_RG -n $Imdb_Aci --image retaildevcrew/imdb-import --restart-policy Never --command-line "dotnet imdb-import.dll ${Imdb_Name} $(eval ${Imdb_RW_Key}) ${Imdb_DB $Imdb_Col}"
```
Might need to mess with the bash parameter substitution inside the quotes.

**Comment by bartr** [comment]
Reviewed in triage and decided to leave as-is for simplicity
